#!/usr/bin/env python3

import os
import json


def _repr(text: str, /) -> str:
    """Return a triple-single-quoted representation of text."""
    if "'''" not in text:
        return f"r'''{text}'''"
    text = text.replace("\\", "\\\\").replace("'''", r"\'\'\'")
    return f"'''{text}'''"


PYDOC_TOOL_ROOT = os.path.realpath(os.path.dirname(__file__))
SOURCE_ROOT = os.path.realpath(os.path.join(PYDOC_TOOL_ROOT, "..", ".."))
PYDOC_BESPOKE_HELP_INPUT_DIR = os.path.join(PYDOC_TOOL_ROOT, "bespoke")
PYDOC_BESPOKE_HELP_TOPICS_DIR = os.path.join(PYDOC_BESPOKE_HELP_INPUT_DIR, "topics")
PYDOC_BESPOKE_HELP_OUTPUT_FILE = os.path.join(
    SOURCE_ROOT, "Lib", "pydoc_data", "bespoke_help.py"
)

bespoke_help = {}
for filename in os.listdir(PYDOC_BESPOKE_HELP_TOPICS_DIR):
    if not filename.endswith(".txt"):
        continue
    helpname = filename.rsplit(".")[0]
    with open(os.path.join(PYDOC_BESPOKE_HELP_TOPICS_DIR, filename)) as f:
        helptext = f.read().strip()

    bespoke_help[helpname] = helptext.strip()

with open(PYDOC_BESPOKE_HELP_OUTPUT_FILE, "w") as f:
    print("# This file was auto-generated by Tools/pydoc/make_bespoke_help.py", file=f)
    print(
        "# See Tools/pydoc/README for info about adding new specialized help.\n", file=f
    )
    with open(os.path.join(PYDOC_BESPOKE_HELP_INPUT_DIR, "base.py")) as base:
        print(base.read(), file=f)
    for name, text in bespoke_help.items():
        print(file=f)
        print(f"def _help_{name}():\n    return {_repr(text)}", file=f)
