#!/usr/bin/env python3

import os
import tomllib


def _repr(text: str, /) -> str:
    """Return a triple-single-quoted representation of text."""
    if "'''" not in text:
        return f"r'''{text}'''"
    text = text.replace("\\", "\\\\").replace("'''", r"\'\'\'")
    return f"'''{text}'''"


ROOT = os.path.realpath(os.path.dirname(__file__))
SOURCE_ROOT = os.path.realpath(os.path.join(ROOT, "..", ".."))
INPUT_DIR = os.path.join(ROOT, "bespoke")
TOPICS_DIR = os.path.join(INPUT_DIR, "topics")
EXTERNAL_DIR = os.path.join(INPUT_DIR, "external")
OUTPUT_FILE = os.path.join(SOURCE_ROOT, "Lib", "pydoc_data", "bespoke_help.py")

bespoke_help = {}
for filename in os.listdir(TOPICS_DIR):
    if not filename.endswith(".txt"):
        continue
    with open(os.path.join(TOPICS_DIR, filename)) as f:
        helptext = f.read().strip()

    bespoke_help[filename.removesuffix(".txt")] = helptext.strip()

external_modules = {}
for filename in os.listdir(EXTERNAL_DIR):
    if not filename.endswith(".toml"):
        continue
    with open(os.path.join(EXTERNAL_DIR, filename), "rb") as f:
        kwargs = tomllib.load(f)
    external_modules[kwargs["name"]] = kwargs


with open(OUTPUT_FILE, "w") as f:
    print(
        "# This file was auto-generated by Tools/pydoc/make_bespoke_help.py",
        file=f,
    )
    print(
        "# See Tools/pydoc/README for info about adding new specialized help.\n",
        file=f,
    )
    with open(os.path.join(INPUT_DIR, "base.py")) as base:
        print(base.read(), file=f)
    for name, text in bespoke_help.items():
        print(file=f)
        print(f"def _help_{name}():\n    return {_repr(text)}", file=f)

    for name, args in external_modules.items():
        print(f"_help_{name} = external(", file=f)
        for arg, val in args.items():
            print(f"    {arg}={_repr(val)},", file=f)
        print(")", file=f)
