# This file was auto-generated by Tools/pydoc/make_bespoke_help.py
# See Tools/pydoc/README for info about adding new specialized help.

import textwrap

# utility functions


def get(name):
    direct_lookup = globals().get(f"_help_{name}", None)
    if direct_lookup is not None:
        return direct_lookup

    return _symbol_lookup.get(name, None)


def external(name=None, description=None, url=None, install_url=None):
    def _external_help():
        out = [description.strip()]
        if url is not None:
            out.append(f"For information about {name}, see:\n    {url}")
        try:
            __import__(name)
        except ImportError:
            if install_url is not None:
                out.append(
                    textwrap.dedent(f"""\
                    You do not currently have {name} installed for this version of Python.
                    For information about installing {name}, see:
                        {install_url}
                """)
                )
        return "\n\n".join(s.strip() for s in out if s is not None)

    return _external_help


# specific help functions
# def help_MY_TOPIC() -> str:
#   ...


# a place to add symbols that can't be represented by filenames
# _symbol_lookup['MY_TOPIC'] = lambda() ->str: ...
_symbol_lookup = {}


# auto-generated help functions


def _help___name__():
    return r'''__name__ is a special variable attached to certain objects.

1. module.__name__ represents the name of the associated module.
   For example:

       >>> import math
       >>> math.__name__
       'math'

   If the module is run as the main module the value is "__main__",
   which provides an idiom for detecting whether a module has been run
   directly, versus imported, by checking if __name__ == "__main__"

2. If obj is a class, function, method, descriptor, or generator, then
   obj.__name__ represents the name that the class cls was given at
   definition time.'''

def _help_tutorial():
    return r'''If you are new to Python (but not new to programming in general), a
tutorial is available online that introduces the basic concepts and
features of the Python language and system:

    https://docs.python.org/tutorial'''
_help_numpy = external(
    name=r'''numpy''',
    description=r'''NumPy is a popular package for numerical/scientific computing in Python.
''',
    url=r'''https://numpy.org/''',
    install_url=r'''https://numpy.org/install/''',
)
_help_pip = external(
    name=r'''pip''',
    description=r'''pip is the package installer for Python. You can use it to install
packages from the Python Package Index and other indexes.
''',
    url=r'''https://pip.pypa.io/''',
    install_url=r'''https://pip.pypa.io/en/stable/installation/''',
)
