# This file was auto-generated by Tools/pydoc/make_bespoke_help.py
# See Tools/pydoc/README for info about adding new specialized help.

def get(name):
    direct_lookup = globals().get(f"_help_{name}", None)
    if direct_lookup is not None:
        return direct_lookup

    return _symbol_lookup.get(name, lambda: "")


# functions for programmatically-generated help text

import io
import random


def _help_pip():
    out = io.StringIO()
    print("""\
pip is the package installer for Python. You can use it to install packages
from the Python Package Index and other indexes.

For information about using pip, see:
    https://pip.pypa.io/en/stable/getting-started/
""".rstrip(), file=out)

    try:
        import pip
    except ImportError:
        print(
            """

It does not appear that you have pip available.  For information about
installing pip, see:
    https://pip.pypa.io/en/stable/installation/
""".rstrip(),
            file=out,
        )

    return out.getvalue()


# lookup table for symbols that can't be listed as names
_symbol_lookup = {}


def _help___name__():
    return r'''__name__ is a special variable attached to certain objects.

1. module.__name__ represents the name of the associated module.
   For example:

       >>> import math
       >>> math.__name__
       'math'

   If the module is run as the main module the value is "__main__",
   which provides an idiom for detecting whether a module has been run
   directly, versus imported (see below).

2. cls.__name__ represents the name that the class cls was given at
   definition time.

3. func.__name__ represents the name that the function func was given at
   definition time.'''
