# Autogenerated by Sphinx on Tue Aug 12 15:42:56 2025
# as part of the release process.

library = {
    '__future__': r'''Imports of the form "from __future__ import feature" are called future
statements. These are special-cased by the Python compiler to allow
the use of new Python features in modules containing the future
statement before the release in which the feature becomes standard.''',
    '_thread': r'''This module provides low-level primitives for working with multiple
threads (also called *light-weight processes* or *tasks*) — multiple
threads of control sharing their global data space.  For
synchronization, simple locks (also called *mutexes* or *binary
semaphores*) are provided. The "threading" module provides an easier
to use and higher-level threading API built on top of this module.''',
    'abc': r'''This module provides the infrastructure for defining *abstract base
classes* (ABCs) in Python, as outlined in **PEP 3119**; see the PEP
for why this was added to Python. (See also **PEP 3141** and the
"numbers" module regarding a type hierarchy for numbers based on
ABCs.)''',
    'aifc': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "aifc" module was Python
3.12.''',
    'annotationlib': r'''The "annotationlib" module provides tools for introspecting
*annotations* on modules, classes, and functions.''',
    'argparse': r'''While "argparse" is the default recommended standard library module
for implementing basic command line applications, authors with more
exacting requirements for exactly how their command line applications
behave may find it doesn’t provide the necessary level of control.
Refer to Choosing an argument parsing library for alternatives to
consider when "argparse" doesn’t support behaviors that the
application requires (such as entirely disabling support for
interspersed options and positional arguments, or accepting option
parameter values that start with "-" even when they correspond to
another defined option).''',
    'array': r'''This module defines an object type which can compactly represent an
array of basic values: characters, integers, floating-point numbers.
Arrays are sequence types and behave very much like lists, except that
the type of objects stored in them is constrained.  The type is
specified at object creation time by using a *type code*, which is a
single character.  The following type codes are defined:''',
    'ast': r'''The "ast" module helps Python applications to process trees of the
Python abstract syntax grammar.  The abstract syntax itself might
change with each Python release; this module helps to find out
programmatically what the current grammar looks like.''',
    'asynchat': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.12 after being deprecated in Python 3.6.  The
removal was decided in **PEP 594**.

Applications should use the "asyncio" module instead.

The last version of Python that provided the "asynchat" module was
Python 3.11.''',
    'asyncio': r'''asyncio is a library to write **concurrent** code using the
**async/await** syntax.''',
    'asyncio-api-index': r'''This page lists all high-level async/await enabled asyncio APIs.''',
    'asyncio-dev': r'''Asynchronous programming is different from classic “sequential”
programming.''',
    'asyncio-eventloop': r'''The event loop is the core of every asyncio application. Event loops
run asynchronous tasks and callbacks, perform network IO operations,
and run subprocesses.''',
    'asyncio-exceptions': r'''A deprecated alias of "TimeoutError", raised when the operation has
exceeded the given deadline.''',
    'asyncio-extending': r'''The main direction for "asyncio" extending is writing custom *event
loop* classes. Asyncio has helpers that could be used to simplify this
task.''',
    'asyncio-future': r'''*Future* objects are used to bridge **low-level callback-based code**
with high-level async/await code.''',
    'asyncio-graph': r'''asyncio has powerful runtime call graph introspection utilities to
trace the entire call graph of a running *coroutine* or *task*, or a
suspended *future*.  These utilities and the underlying machinery can
be used from within a Python program or by external profilers and
debuggers.''',
    'asyncio-llapi-index': r'''This page lists all low-level asyncio APIs.''',
    'asyncio-platforms': r'''The "asyncio" module is designed to be portable, but some platforms
have subtle differences and limitations due to the platforms’
underlying architecture and capabilities.''',
    'asyncio-policy': r'''Policies are deprecated and will be removed in Python 3.16. Users are
encouraged to use the "asyncio.run()" function or the "asyncio.Runner"
with *loop_factory* to use the desired loop implementation.''',
    'asyncio-protocol': r'''Transports and Protocols are used by the **low-level** event loop APIs
such as "loop.create_connection()".  They use callback-based
programming style and enable high-performance implementations of
network or IPC protocols (e.g. HTTP).''',
    'asyncio-queue': r'''asyncio queues are designed to be similar to classes of the "queue"
module.  Although asyncio queues are not thread-safe, they are
designed to be used specifically in async/await code.''',
    'asyncio-runner': r'''This section outlines high-level asyncio primitives to run asyncio
code.''',
    'asyncio-stream': r'''Streams are high-level async/await-ready primitives to work with
network connections.  Streams allow sending and receiving data without
using callbacks or low-level protocols and transports.''',
    'asyncio-subprocess': r'''This section describes high-level async/await asyncio APIs to create
and manage subprocesses.''',
    'asyncio-sync': r'''asyncio synchronization primitives are designed to be similar to those
of the "threading" module with two important caveats:''',
    'asyncio-task': r'''This section outlines high-level asyncio APIs to work with coroutines
and Tasks.''',
    'asyncore': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.12 after being deprecated in Python 3.6.  The
removal was decided in **PEP 594**.

Applications should use the "asyncio" module instead.

The last version of Python that provided the "asyncore" module was
Python 3.11.''',
    'atexit': r'''The "atexit" module defines functions to register and unregister
cleanup functions.  Functions thus registered are automatically
executed upon normal interpreter termination.  "atexit" runs these
functions in the *reverse* order in which they were registered; if you
register "A", "B", and "C", at interpreter termination time they will
be run in the order "C", "B", "A".''',
    'audioop': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "audioop" module was
Python 3.12.''',
    'audit_events': r'''This table contains all events raised by "sys.audit()" or
"PySys_Audit()" calls throughout the CPython runtime and the standard
library.  These calls were added in 3.8 or later (see **PEP 578**).''',
    'base64': r'''This module provides functions for encoding binary data to printable
ASCII characters and decoding such encodings back to binary data. This
includes the encodings specified in **RFC 4648** (Base64, Base32 and
Base16) and the non-standard Base85 encodings.''',
    'bdb': r'''The "bdb" module handles basic debugger functions, like setting
breakpoints or managing execution via the debugger.''',
    'binascii': r'''The "binascii" module contains a number of methods to convert between
binary and various ASCII-encoded binary representations. Normally, you
will not use these functions directly but use wrapper modules like
"base64" instead. The "binascii" module contains low-level functions
written in C for greater speed that are used by the higher-level
modules.''',
    'bisect': r'''This module provides support for maintaining a list in sorted order
without having to sort the list after each insertion.  For long lists
of items with expensive comparison operations, this can be an
improvement over linear searches or frequent resorting.''',
    'builtins': r'''This module provides direct access to all ‘built-in’ identifiers of
Python; for example, "builtins.open" is the full name for the built-in
function "open()".''',
    'bz2': r'''This module provides a comprehensive interface for compressing and
decompressing data using the bzip2 compression algorithm.''',
    'calendar': r'''This module allows you to output calendars like the Unix **cal**
program, and provides additional useful functions related to the
calendar. By default, these calendars have Monday as the first day of
the week, and Sunday as the last (the European convention). Use
"setfirstweekday()" to set the first day of the week to Sunday (6) or
to any other weekday.  Parameters that specify dates are given as
integers. For related functionality, see also the "datetime" and
"time" modules.''',
    'cgi': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

A fork of the module on PyPI can be used instead: legacy-cgi. This is
a copy of the cgi module, no longer maintained or supported by the
core Python team.

The last version of Python that provided the "cgi" module was Python
3.12.''',
    'cgitb': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

A fork of the module on PyPI can now be used instead: legacy-cgi. This
is a copy of the cgi module, no longer maintained or supported by the
core Python team.

The last version of Python that provided the "cgitb" module was Python
3.12.''',
    'chunk': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "chunk" module was Python
3.12.''',
    'cmath': r'''This module provides access to mathematical functions for complex
numbers.  The functions in this module accept integers, floating-point
numbers or complex numbers as arguments. They will also accept any
Python object that has either a "__complex__()" or a "__float__()"
method: these methods are used to convert the object to a complex or
floating-point number, respectively, and the function is then applied
to the result of the conversion.''',
    'cmd': r'''The "Cmd" class provides a simple framework for writing line-oriented
command interpreters.  These are often useful for test harnesses,
administrative tools, and prototypes that will later be wrapped in a
more sophisticated interface.''',
    'cmdline': r'''The following modules have a command-line interface.''',
    'code': r'''The "code" module provides facilities to implement read-eval-print
loops in Python.  Two classes and convenience functions are included
which can be used to build applications which provide an interactive
interpreter prompt.''',
    'codecs': r'''This module defines base classes for standard Python codecs (encoders
and decoders) and provides access to the internal Python codec
registry, which manages the codec and error handling lookup process.
Most standard codecs are *text encodings*, which encode text to bytes
(and decode bytes to text), but there are also codecs provided that
encode text to text, and bytes to bytes. Custom codecs may encode and
decode between arbitrary types, but some module features are
restricted to be used specifically with *text encodings* or with
codecs that encode to "bytes".''',
    'codeop': r'''The "codeop" module provides utilities upon which the Python read-
eval-print loop can be emulated, as is done in the "code" module.  As
a result, you probably don’t want to use the module directly; if you
want to include such a loop in your program you probably want to use
the "code" module instead.''',
    'collections': r'''This module implements specialized container datatypes providing
alternatives to Python’s general purpose built-in containers, "dict",
"list", "set", and "tuple".''',
    'collections.abc': r'''This module provides *abstract base classes* that can be used to test
whether a class provides a particular interface; for example, whether
it is *hashable* or whether it is a *mapping*.''',
    'colorsys': r'''The "colorsys" module defines bidirectional conversions of color
values between colors expressed in the RGB (Red Green Blue) color
space used in computer monitors and three other coordinate systems:
YIQ, HLS (Hue Lightness Saturation) and HSV (Hue Saturation Value).
Coordinates in all of these color spaces are floating-point values.
In the YIQ space, the Y coordinate is between 0 and 1, but the I and Q
coordinates can be positive or negative.  In all other spaces, the
coordinates are all between 0 and 1.''',
    'compileall': r'''This module provides some utility functions to support installing
Python libraries.  These functions compile Python source files in a
directory tree. This module can be used to create the cached byte-code
files at library installation time, which makes them available for use
even by users who don’t have write permission to the library
directories.''',
    'compression': r'''The "compression" package contains the canonical compression modules
containing interfaces to several different compression algorithms.
Some of these modules have historically been available as separate
modules; those will continue to be available under their original
names for compatibility reasons, and will not be removed without a
deprecation cycle. The use of modules in "compression" is encouraged
where practical.''',
    'compression.zstd': r'''This module provides classes and functions for compressing and
decompressing data using the Zstandard (or *zstd*) compression
algorithm. The zstd manual describes Zstandard as “a fast lossless
compression algorithm, targeting real-time compression scenarios at
zlib-level and better compression ratios.” Also included is a file
interface that supports reading and writing the contents of ".zst"
files created by the **zstd** utility, as well as raw zstd compressed
streams.''',
    'concurrent': r'''This package contains the following modules:''',
    'concurrent.futures': r'''The "concurrent.futures" module provides a high-level interface for
asynchronously executing callables.''',
    'concurrent.interpreters': r'''The "concurrent.interpreters" module constructs higher-level
interfaces on top of the lower level "_interpreters" module.''',
    'configparser': r'''This module provides the "ConfigParser" class which implements a basic
configuration language which provides a structure similar to what’s
found in Microsoft Windows INI files.  You can use this to write
Python programs which can be customized by end users easily.''',
    'constants': r'''A small number of constants live in the built-in namespace.  They are:''',
    'contextlib': r'''This module provides utilities for common tasks involving the "with"
statement. For more information see also Context Manager Types and
With Statement Context Managers.''',
    'contextvars': r'''This module provides APIs to manage, store, and access context-local
state.  The "ContextVar" class is used to declare and work with
*Context Variables*.  The "copy_context()" function and the "Context"
class should be used to manage the current context in asynchronous
frameworks.''',
    'copy': r'''Assignment statements in Python do not copy objects, they create
bindings between a target and an object. For collections that are
mutable or contain mutable items, a copy is sometimes needed so one
can change one copy without changing the other. This module provides
generic shallow and deep copy operations (explained below).''',
    'copyreg': r'''The "copyreg" module offers a way to define functions used while
pickling specific objects.  The "pickle" and "copy" modules use those
functions when pickling/copying those objects.  The module provides
configuration information about object constructors which are not
classes. Such constructors may be factory functions or class
instances.''',
    'crypt': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

Applications can use the "hashlib" module from the standard library.
Other possible replacements are third-party libraries from PyPI:
legacycrypt, bcrypt, argon2-cffi, or passlib. These are not supported
or maintained by the Python core team.

The last version of Python that provided the "crypt" module was Python
3.12.''',
    'csv': r'''The so-called CSV (Comma Separated Values) format is the most common
import and export format for spreadsheets and databases.  CSV format
was used for many years prior to attempts to describe the format in a
standardized way in **RFC 4180**.  The lack of a well-defined standard
means that subtle differences often exist in the data produced and
consumed by different applications.  These differences can make it
annoying to process CSV files from multiple sources. Still, while the
delimiters and quoting characters vary, the overall format is similar
enough that it is possible to write a single module which can
efficiently manipulate such data, hiding the details of reading and
writing the data from the programmer.''',
    'ctypes': r'''"ctypes" is a foreign function library for Python.  It provides C
compatible data types, and allows calling functions in DLLs or shared
libraries.  It can be used to wrap these libraries in pure Python.''',
    'curses': r'''The "curses" module provides an interface to the curses library, the
de-facto standard for portable advanced terminal handling.''',
    'curses.ascii': r'''The "curses.ascii" module supplies name constants for ASCII characters
and functions to test membership in various ASCII character classes.
The constants supplied are names for control characters as follows:''',
    'curses.panel': r'''Panels are windows with the added feature of depth, so they can be
stacked on top of each other, and only the visible portions of each
window will be displayed.  Panels can be added, moved up or down in
the stack, and removed.''',
    'dataclasses': r'''This module provides a decorator and functions for automatically
adding generated *special methods* such as "__init__()" and
"__repr__()" to user-defined classes.  It was originally described in
**PEP 557**.''',
    'datetime': r'''The "datetime" module supplies classes for manipulating dates and
times.''',
    'dbm': r'''"dbm" is a generic interface to variants of the DBM database:''',
    'debug': r'''These libraries help you with Python development: the debugger enables
you to step through code, analyze stack frames and set breakpoints
etc., and the profilers run code and give you a detailed breakdown of
execution times, allowing you to identify bottlenecks in your
programs. Auditing events provide visibility into runtime behaviors
that would otherwise require intrusive debugging or patching.''',
    'decimal': r'''The "decimal" module provides support for fast correctly rounded
decimal floating-point arithmetic. It offers several advantages over
the "float" datatype:''',
    'devmode': r'''The Python Development Mode introduces additional runtime checks that
are too expensive to be enabled by default. It should not be more
verbose than the default if the code is correct; new warnings are only
emitted when an issue is detected.''',
    'dialog': r'''The "tkinter.simpledialog" module contains convenience classes and
functions for creating simple modal dialogs to get a value from the
user.''',
    'difflib': r'''This module provides classes and functions for comparing sequences. It
can be used for example, for comparing files, and can produce
information about file differences in various formats, including HTML
and context and unified diffs. For comparing directories and files,
see also, the "filecmp" module.''',
    'dis': r'''The "dis" module supports the analysis of CPython *bytecode* by
disassembling it. The CPython bytecode which this module takes as an
input is defined in the file "Include/opcode.h" and used by the
compiler and the interpreter.''',
    'distribution': r'''These libraries help you with publishing and installing Python
software. While these modules are designed to work in conjunction with
the Python Package Index, they can also be used with a local index
server, or without any index server at all.''',
    'distutils': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.12 after being deprecated in Python 3.10.  The
removal was decided in **PEP 632**, which has migration advice.

The last version of Python that provided the "distutils" module was
Python 3.11.''',
    'doctest': r'''The "doctest" module searches for pieces of text that look like
interactive Python sessions, and then executes those sessions to
verify that they work exactly as shown.  There are several common ways
to use doctest:''',
    'email': r'''The "email" package is a library for managing email messages.  It is
specifically *not* designed to do any sending of email messages to
SMTP (**RFC 2821**), NNTP, or other servers; those are functions of
modules such as "smtplib".  The "email" package attempts to be as RFC-
compliant as possible, supporting **RFC 5322** and **RFC 6532**, as
well as such MIME-related RFCs as **RFC 2045**, **RFC 2046**, **RFC
2047**, **RFC 2183**, and **RFC 2231**.''',
    'email.charset': r'''This module is part of the legacy ("Compat32") email API.  In the new
API only the aliases table is used.''',
    'email.compat32-message': r'''The "Message" class is very similar to the "EmailMessage" class,
without the methods added by that class, and with the default behavior
of certain other methods being slightly different.  We also document
here some methods that, while supported by the "EmailMessage" class,
are not recommended unless you are dealing with legacy code.''',
    'email.contentmanager': r'''Base class for content managers.  Provides the standard registry
mechanisms to register converters between MIME content and other
representations, as well as the "get_content" and "set_content"
dispatch methods.''',
    'email.encoders': r'''This module is part of the legacy ("Compat32") email API.  In the new
API the functionality is provided by the *cte* parameter of the
"set_content()" method.''',
    'email.errors': r'''The following exception classes are defined in the "email.errors"
module:''',
    'email.examples': r'''Here are a few examples of how to use the "email" package to read,
write, and send simple email messages, as well as more complex MIME
messages.''',
    'email.generator': r'''One of the most common tasks is to generate the flat (serialized)
version of the email message represented by a message object
structure.  You will need to do this if you want to send your message
via "smtplib.SMTP.sendmail()", or print the message on the console.
Taking a message object structure and producing a serialized
representation is the job of the generator classes.''',
    'email.header': r'''This module is part of the legacy ("Compat32") email API.  In the
current API encoding and decoding of headers is handled transparently
by the dictionary-like API of the "EmailMessage" class.  In addition
to uses in legacy code, this module can be useful in applications that
need to completely control the character sets used when encoding
headers.''',
    'email.headerregistry': r'''Headers are represented by customized subclasses of "str".  The
particular class used to represent a given header is determined by the
"header_factory" of the "policy" in effect when the headers are
created.  This section documents the particular "header_factory"
implemented by the email package for handling **RFC 5322** compliant
email messages, which not only provides customized header objects for
various header types, but also provides an extension mechanism for
applications to add their own custom header types.''',
    'email.iterators': r'''Iterating over a message object tree is fairly easy with the
"Message.walk" method.  The "email.iterators" module provides some
useful higher level iterations over message object trees.''',
    'email.message': r'''The central class in the "email" package is the "EmailMessage" class,
imported from the "email.message" module.  It is the base class for
the "email" object model.  "EmailMessage" provides the core
functionality for setting and querying header fields, for accessing
message bodies, and for creating or modifying structured messages.''',
    'email.mime': r'''This module is part of the legacy ("Compat32") email API.  Its
functionality is partially replaced by the "contentmanager" in the new
API, but in certain applications these classes may still be useful,
even in non-legacy code.''',
    'email.parser': r'''Message object structures can be created in one of two ways: they can
be created from whole cloth by creating an "EmailMessage" object,
adding headers using the dictionary interface, and adding payload(s)
using "set_content()" and related methods, or they can be created by
parsing a serialized representation of the email message.''',
    'email.policy': r'''The "email" package’s prime focus is the handling of email messages as
described by the various email and MIME RFCs.  However, the general
format of email messages (a block of header fields each consisting of
a name followed by a colon followed by a value, the whole block
followed by a blank line and an arbitrary ‘body’), is a format that
has found utility outside of the realm of email.  Some of these uses
conform fairly closely to the main email RFCs, some do not.  Even when
working with email, there are times when it is desirable to break
strict compliance with the RFCs, such as generating emails that
interoperate with email servers that do not themselves follow the
standards, or that implement extensions you want to use in ways that
violate the standards.''',
    'email.utils': r'''There are a couple of useful utilities provided in the "email.utils"
module:''',
    'ensurepip': r'''The "ensurepip" package provides support for bootstrapping the "pip"
installer into an existing Python installation or virtual environment.
This bootstrapping approach reflects the fact that "pip" is an
independent project with its own release cycle, and the latest
available stable version is bundled with maintenance and feature
releases of the CPython reference interpreter.''',
    'enum': r'''This page contains the API reference information. For tutorial
information and discussion of more advanced topics, see''',
    'errno': r'''This module makes available standard "errno" system symbols. The value
of each symbol is the corresponding integer value. The names and
descriptions are borrowed from "linux/include/errno.h", which should
be all-inclusive.''',
    'exceptions': r'''In Python, all exceptions must be instances of a class that derives
from "BaseException".  In a "try" statement with an "except" clause
that mentions a particular class, that clause also handles any
exception classes derived from that class (but not exception classes
from which *it* is derived).  Two exception classes that are not
related via subclassing are never equivalent, even if they have the
same name.''',
    'faulthandler': r'''This module contains functions to dump Python tracebacks explicitly,
on a fault, after a timeout, or on a user signal. Call
"faulthandler.enable()" to install fault handlers for the "SIGSEGV",
"SIGFPE", "SIGABRT", "SIGBUS", and "SIGILL" signals. You can also
enable them at startup by setting the "PYTHONFAULTHANDLER" environment
variable or by using the "-X" "faulthandler" command line option.''',
    'fcntl': r'''This module performs file and I/O control on file descriptors. It is
an interface to the "fcntl()" and "ioctl()" Unix routines. See the
*fcntl(2)* and *ioctl(2)* Unix manual pages for full details.''',
    'filecmp': r'''The "filecmp" module defines functions to compare files and
directories, with various optional time/correctness trade-offs. For
comparing files, see also the "difflib" module.''',
    'fileinput': r'''This module implements a helper class and functions to quickly write a
loop over standard input or a list of files. If you just want to read
or write one file see "open()".''',
    'fnmatch': r'''This module provides support for Unix shell-style wildcards, which are
*not* the same as regular expressions (which are documented in the
"re" module).  The special characters used in shell-style wildcards
are:''',
    'fractions': r'''The "fractions" module provides support for rational number
arithmetic.''',
    'ftplib': r'''This module defines the class "FTP" and a few related items. The "FTP"
class implements the client side of the FTP protocol.  You can use
this to write Python programs that perform a variety of automated FTP
jobs, such as mirroring other FTP servers.  It is also used by the
module "urllib.request" to handle URLs that use FTP.  For more
information on FTP (File Transfer Protocol), see internet **RFC 959**.''',
    'functions': r'''The Python interpreter has a number of functions and types built into
it that are always available.  They are listed here in alphabetical
order.''',
    'functools': r'''The "functools" module is for higher-order functions: functions that
act on or return other functions. In general, any callable object can
be treated as a function for the purposes of this module.''',
    'gc': r'''This module provides an interface to the optional garbage collector.
It provides the ability to disable the collector, tune the collection
frequency, and set debugging options.  It also provides access to
unreachable objects that the collector found but cannot free.  Since
the collector supplements the reference counting already used in
Python, you can disable the collector if you are sure your program
does not create reference cycles.  Automatic collection can be
disabled by calling "gc.disable()".  To debug a leaking program call
"gc.set_debug(gc.DEBUG_LEAK)". Notice that this includes
"gc.DEBUG_SAVEALL", causing garbage-collected objects to be saved in
gc.garbage for inspection.''',
    'getopt': r'''This module is considered feature complete. A more declarative and
extensible alternative to this API is provided in the "optparse"
module. Further functional enhancements for command line parameter
processing are provided either as third party modules on PyPI, or else
as features in the "argparse" module.''',
    'getpass': r'''Availability: not WASI.''',
    'gettext': r'''The "gettext" module provides internationalization (I18N) and
localization (L10N) services for your Python modules and applications.
It supports both the GNU **gettext** message catalog API and a higher
level, class-based API that may be more appropriate for Python files.
The interface described below allows you to write your module and
application messages in one natural language, and provide a catalog of
translated messages for running under different natural languages.''',
    'glob': r'''The "glob" module finds all the pathnames matching a specified pattern
according to the rules used by the Unix shell, although results are
returned in arbitrary order.  No tilde expansion is done, but "*",
"?", and character ranges expressed with "[]" will be correctly
matched.  This is done by using the "os.scandir()" and
"fnmatch.fnmatch()" functions in concert, and not by actually invoking
a subshell.''',
    'graphlib': r'''Provides functionality to topologically sort a graph of *hashable*
nodes.''',
    'grp': r'''This module provides access to the Unix group database. It is
available on all Unix versions.''',
    'gzip': r'''This module provides a simple interface to compress and decompress
files just like the GNU programs **gzip** and **gunzip** would.''',
    'hashlib': r'''This module implements a common interface to many different hash
algorithms. Included are the FIPS secure hash algorithms SHA224,
SHA256, SHA384, SHA512, (defined in the FIPS 180-4 standard), the
SHA-3 series (defined in the FIPS 202 standard) as well as the legacy
algorithms SHA1 (formerly part of FIPS) and the MD5 algorithm (defined
in internet **RFC 1321**).''',
    'heapq': r'''This module provides an implementation of the heap queue algorithm,
also known as the priority queue algorithm.''',
    'hmac': r'''This module implements the HMAC algorithm as described by **RFC
2104**. The interface allows to use any hash function with a *fixed*
digest size. In particular, extendable output functions such as
SHAKE-128 or SHAKE-256 cannot be used with HMAC.''',
    'html': r'''This module defines utilities to manipulate HTML.''',
    'html.entities': r'''This module defines four dictionaries, "html5", "name2codepoint",
"codepoint2name", and "entitydefs".''',
    'html.parser': r'''This module defines a class "HTMLParser" which serves as the basis for
parsing text files formatted in HTML (HyperText Mark-up Language) and
XHTML.''',
    'http': r'''"http" is a package that collects several modules for working with the
HyperText Transfer Protocol:''',
    'http.client': r'''This module defines classes that implement the client side of the HTTP
and HTTPS protocols.  It is normally not used directly — the module
"urllib.request" uses it to handle URLs that use HTTP and HTTPS.''',
    'http.cookiejar': r'''The "http.cookiejar" module defines classes for automatic handling of
HTTP cookies.  It is useful for accessing web sites that require small
pieces of data – *cookies* – to be set on the client machine by an
HTTP response from a web server, and then returned to the server in
later HTTP requests.''',
    'http.cookies': r'''The "http.cookies" module defines classes for abstracting the concept
of cookies, an HTTP state management mechanism. It supports both
simple string-only cookies, and provides an abstraction for having any
serializable data-type as cookie value.''',
    'http.server': r'''This module defines classes for implementing HTTP servers.''',
    'idle': r'''IDLE is Python’s Integrated Development and Learning Environment.''',
    'imaplib': r'''This module defines three classes, "IMAP4", "IMAP4_SSL" and
"IMAP4_stream", which encapsulate a connection to an IMAP4 server and
implement a large subset of the IMAP4rev1 client protocol as defined
in **RFC 2060**. It is backward compatible with IMAP4 (**RFC 1730**)
servers, but note that the "STATUS" command is not supported in IMAP4.''',
    'imghdr': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

Possible replacements are third-party libraries from PyPI: filetype,
puremagic, or python-magic. These are not supported or maintained by
the Python core team.

The last version of Python that provided the "imghdr" module was
Python 3.12.''',
    'imp': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.12 after being deprecated in Python 3.4.

The removal notice includes guidance for migrating code from "imp" to
"importlib".

The last version of Python that provided the "imp" module was Python
3.11.''',
    'importlib': r'''The purpose of the "importlib" package is three-fold.''',
    'importlib.metadata': r'''Changed in version 3.10: "importlib.metadata" is no longer
provisional.''',
    'importlib.resources': r'''This module leverages Python’s import system to provide access to
*resources* within *packages*.''',
    'importlib.resources.abc': r'''*Superseded by TraversableResources*''',
    'index': r'''While The Python Language Reference describes the exact syntax and
semantics of the Python language, this library reference manual
describes the standard library that is distributed with Python. It
also describes some of the optional components that are commonly
included in Python distributions.''',
    'inspect': r'''The "inspect" module provides several useful functions to help get
information about live objects such as modules, classes, methods,
functions, tracebacks, frame objects, and code objects.  For example,
it can help you examine the contents of a class, retrieve the source
code of a method, extract and format the argument list for a function,
or get all the information you need to display a detailed traceback.''',
    'intro': r'''The “Python library” contains several different kinds of components.''',
    'io': r'''The "io" module provides Python’s main facilities for dealing with
various types of I/O.  There are three main types of I/O: *text I/O*,
*binary I/O* and *raw I/O*.  These are generic categories, and various
backing stores can be used for each of them.  A concrete object
belonging to any of these categories is called a *file object*.  Other
common terms are *stream* and *file-like object*.''',
    'ipaddress': r'''"ipaddress" provides the capabilities to create, manipulate and
operate on IPv4 and IPv6 addresses and networks.''',
    'itertools': r'''This module implements a number of *iterator* building blocks inspired
by constructs from APL, Haskell, and SML.  Each has been recast in a
form suitable for Python.''',
    'json': r'''JSON (JavaScript Object Notation), specified by **RFC 7159** (which
obsoletes **RFC 4627**) and by ECMA-404, is a lightweight data
interchange format inspired by JavaScript object literal syntax
(although it is not a strict subset of JavaScript [1] ).''',
    'keyword': r'''This module allows a Python program to determine if a string is a
keyword or soft keyword.''',
    'language': r'''Python provides a number of modules to assist in working with the
Python language.  These modules support tokenizing, parsing, syntax
analysis, bytecode disassembly, and various other facilities.''',
    'linecache': r'''The "linecache" module allows one to get any line from a Python source
file, while attempting to optimize internally, using a cache, the
common case where many lines are read from a single file.  This is
used by the "traceback" module to retrieve source lines for inclusion
in  the formatted traceback.''',
    'locale': r'''The "locale" module opens access to the POSIX locale database and
functionality. The POSIX locale mechanism allows programmers to deal
with certain cultural issues in an application, without requiring the
programmer to know all the specifics of each country where the
software is executed.''',
    'logging': r'''This page contains the API reference information. For tutorial
information and discussion of more advanced topics, see''',
    'logging.config': r'''This page contains only reference information. For tutorials, please
see''',
    'logging.handlers': r'''This page contains only reference information. For tutorials, please
see''',
    'lzma': r'''This module provides classes and convenience functions for compressing
and decompressing data using the LZMA compression algorithm. Also
included is a file interface supporting the ".xz" and legacy ".lzma"
file formats used by the **xz** utility, as well as raw compressed
streams.''',
    'mailbox': r'''This module defines two classes, "Mailbox" and "Message", for
accessing and manipulating on-disk mailboxes and the messages they
contain. "Mailbox" offers a dictionary-like mapping from keys to
messages. "Message" extends the "email.message" module’s "Message"
class with format-specific state and behavior. Supported mailbox
formats are Maildir, mbox, MH, Babyl, and MMDF.''',
    'mailcap': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "mailcap" module was
Python 3.12.''',
    'markup': r'''Python supports a variety of modules to work with various forms of
structured data markup.  This includes modules to work with the
Standard Generalized Markup Language (SGML) and the Hypertext Markup
Language (HTML), and several interfaces for working with the
Extensible Markup Language (XML).''',
    'marshal': r'''This module contains functions that can read and write Python values
in a binary format.  The format is specific to Python, but independent
of machine architecture issues (e.g., you can write a Python value to
a file on a PC, transport the file to a Mac, and read it back there).
Details of the format are undocumented on purpose; it may change
between Python versions (although it rarely does). [1]''',
    'math': r'''This module provides access to common mathematical functions and
constants, including those defined by the C standard.''',
    'mimetypes': r'''The "mimetypes" module converts between a filename or URL and the MIME
type associated with the filename extension.  Conversions are provided
from filename to MIME type and from MIME type to filename extension;
encodings are not supported for the latter conversion.''',
    'mmap': r'''Availability: not WASI.''',
    'modulefinder': r'''This module provides a "ModuleFinder" class that can be used to
determine the set of modules imported by a script. "modulefinder.py"
can also be run as a script, giving the filename of a Python script as
its argument, after which a report of the imported modules will be
printed.''',
    'msilib': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "msilib" module was
Python 3.12.''',
    'msvcrt': r'''These functions provide access to some useful capabilities on Windows
platforms. Some higher-level modules use these functions to build the
Windows implementations of their services. For example, the "getpass"
module uses this in the implementation of the "getpass()" function.''',
    'multiprocessing': r'''Availability: not Android, not iOS, not WASI.''',
    'multiprocessing.shared_memory': r'''This module provides a class, "SharedMemory", for the allocation and
management of shared memory to be accessed by one or more processes on
a multicore or symmetric multiprocessor (SMP) machine.  To assist with
the life-cycle management of shared memory especially across distinct
processes, a "BaseManager" subclass, "SharedMemoryManager", is also
provided in the "multiprocessing.managers" module.''',
    'netdata': r'''This chapter describes modules which support handling data formats
commonly used on the internet.''',
    'netrc': r'''The "netrc" class parses and encapsulates the netrc file format used
by the Unix **ftp** program and other FTP clients.''',
    'nis': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "nis" module was Python
3.12.''',
    'nntplib': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "nntplib" module was
Python 3.12.''',
    'numbers': r'''The "numbers" module (**PEP 3141**) defines a hierarchy of numeric
*abstract base classes* which progressively define more operations.
None of the types defined in this module are intended to be
instantiated.''',
    'operator': r'''The "operator" module exports a set of efficient functions
corresponding to the intrinsic operators of Python.  For example,
"operator.add(x, y)" is equivalent to the expression "x+y". Many
function names are those used for special methods, without the double
underscores.  For backward compatibility, many of these have a variant
with the double underscores kept. The variants without the double
underscores are preferred for clarity.''',
    'optparse': r'''The standard library includes three argument parsing libraries:''',
    'os': r'''This module provides a portable way of using operating system
dependent functionality.  If you just want to read or write a file see
"open()", if you want to manipulate paths, see the "os.path" module,
and if you want to read all the lines in all the files on the command
line see the "fileinput" module.  For creating temporary files and
directories see the "tempfile" module, and for high-level file and
directory handling see the "shutil" module.''',
    'os.path': r'''This module implements some useful functions on pathnames. To read or
write files see "open()", and for accessing the filesystem see the
"os" module. The path parameters can be passed as strings, or bytes,
or any object implementing the "os.PathLike" protocol.''',
    'ossaudiodev': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "ossaudiodev" module was
Python 3.12.''',
    'pathlib': r'''This module offers classes representing filesystem paths with
semantics appropriate for different operating systems.  Path classes
are divided between pure paths, which provide purely computational
operations without I/O, and concrete paths, which inherit from pure
paths but also provide I/O operations.''',
    'pdb': r'''The module "pdb" defines an interactive source code debugger for
Python programs.  It supports setting (conditional) breakpoints and
single stepping at the source line level, inspection of stack frames,
source code listing, and evaluation of arbitrary Python code in the
context of any stack frame.  It also supports post-mortem debugging
and can be called under program control.''',
    'pickle': r'''The "pickle" module implements binary protocols for serializing and
de-serializing a Python object structure.  *“Pickling”* is the process
whereby a Python object hierarchy is converted into a byte stream, and
*“unpickling”* is the inverse operation, whereby a byte stream (from a
*binary file* or *bytes-like object*) is converted back into an object
hierarchy.  Pickling (and unpickling) is alternatively known as
“serialization”, “marshalling,” [1] or “flattening”; however, to avoid
confusion, the terms used here are “pickling” and “unpickling”.''',
    'pickletools': r'''This module contains various constants relating to the intimate
details of the "pickle" module, some lengthy comments about the
implementation, and a few useful functions for analyzing pickled data.
The contents of this module are useful for Python core developers who
are working on the "pickle"; ordinary users of the "pickle" module
probably won’t find the "pickletools" module relevant.''',
    'pipes': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

Applications should use the "subprocess" module instead.

The last version of Python that provided the "pipes" module was Python
3.12.''',
    'pkgutil': r'''This module provides utilities for the import system, in particular
package support.''',
    'platform': r'''Specific platforms listed alphabetically, with Linux included in the
Unix section.''',
    'plistlib': r'''This module provides an interface for reading and writing the
“property list” files used by Apple, primarily on macOS and iOS. This
module supports both binary and XML plist files.''',
    'poplib': r'''This module defines a class, "POP3", which encapsulates a connection
to a POP3 server and implements the protocol as defined in **RFC
1939**. The "POP3" class supports both the minimal and optional
command sets from **RFC 1939**. The "POP3" class also supports the
"STLS" command introduced in **RFC 2595** to enable encrypted
communication on an already established connection.''',
    'posix': r'''This module provides access to operating system functionality that is
standardized by the C Standard and the POSIX standard (a thinly
disguised Unix interface).''',
    'pprint': r'''The "pprint" module provides a capability to “pretty-print” arbitrary
Python data structures in a form which can be used as input to the
interpreter. If the formatted structures include objects which are not
fundamental Python types, the representation may not be loadable.
This may be the case if objects such as files, sockets or classes are
included, as well as many other objects which are not representable as
Python literals.''',
    'profile': r'''Python provides both *statistical profiling* and *deterministic
profiling* of Python programs. A *profile* is a set of statistics that
describes how often and for how long various parts of the program
executed. These statistics can be formatted into reports via the
"pstats" module.''',
    'pty': r'''The "pty" module defines operations for handling the pseudo-terminal
concept: starting another process and being able to write to and read
from its controlling terminal programmatically.''',
    'pwd': r'''This module provides access to the Unix user account and password
database.  It is available on all Unix versions.''',
    'py_compile': r'''The "py_compile" module provides a function to generate a byte-code
file from a source file, and another function used when the module
source file is invoked as a script.''',
    'pyclbr': r'''The "pyclbr" module provides limited information about the functions,
classes, and methods defined in a Python-coded module.  The
information is sufficient to implement a module browser.  The
information is extracted from the Python source code rather than by
importing the module, so this module is safe to use with untrusted
code. This restriction makes it impossible to use this module with
modules not implemented in Python, including all standard and optional
extension modules.''',
    'pydoc': r'''The "pydoc" module automatically generates documentation from Python
modules.  The documentation can be presented as pages of text on the
console, served to a web browser, or saved to HTML files.''',
    'pyexpat': r'''If you need to parse untrusted or unauthenticated data, see XML
security.''',
    'queue': r'''The "queue" module implements multi-producer, multi-consumer queues.
It is especially useful in threaded programming when information must
be exchanged safely between multiple threads.  The "Queue" class in
this module implements all the required locking semantics.''',
    'quopri': r'''This module performs quoted-printable transport encoding and decoding,
as defined in **RFC 1521**: “MIME (Multipurpose Internet Mail
Extensions) Part One: Mechanisms for Specifying and Describing the
Format of Internet Message Bodies”. The quoted-printable encoding is
designed for data where there are relatively few nonprintable
characters; the base64 encoding scheme available via the "base64"
module is more compact if there are many such characters, as when
sending a graphics file.''',
    'random': r'''This module implements pseudo-random number generators for various
distributions.''',
    're': r'''This module provides regular expression matching operations similar to
those found in Perl.''',
    'readline': r'''The "readline" module defines a number of functions to facilitate
completion and reading/writing of history files from the Python
interpreter. This module can be used directly, or via the
"rlcompleter" module, which supports completion of Python identifiers
at the interactive prompt.  Settings made using  this module affect
the behaviour of both the interpreter’s interactive prompt  and the
prompts offered by the built-in "input()" function.''',
    'reprlib': r'''The "reprlib" module provides a means for producing object
representations with limits on the size of the resulting strings. This
is used in the Python debugger and may be useful in other contexts as
well.''',
    'resource': r'''This module provides basic mechanisms for measuring and controlling
system resources utilized by a program.''',
    'rlcompleter': r'''The "rlcompleter" module defines a completion function suitable to be
passed to "set_completer()" in the "readline" module.''',
    'runpy': r'''The "runpy" module is used to locate and run Python modules without
importing them first. Its main use is to implement the "-m" command
line switch that allows scripts to be located using the Python module
namespace rather than the filesystem.''',
    'sched': r'''The "sched" module defines a class which implements a general purpose
event scheduler:''',
    'secrets': r'''The "secrets" module is used for generating cryptographically strong
random numbers suitable for managing data such as passwords, account
authentication, security tokens, and related secrets.''',
    'security_warnings': r'''The following modules have specific security considerations:''',
    'select': r'''This module provides access to the "select()" and "poll()" functions
available in most operating systems, "devpoll()" available on Solaris
and derivatives, "epoll()" available on Linux 2.5+ and "kqueue()"
available on most BSD. Note that on Windows, it only works for
sockets; on other operating systems, it also works for other file
types (in particular, on Unix, it works on pipes). It cannot be used
on regular files to determine whether a file has grown since it was
last read.''',
    'selectors': r'''This module allows high-level and efficient I/O multiplexing, built
upon the "select" module primitives. Users are encouraged to use this
module instead, unless they want precise control over the OS-level
primitives used.''',
    'shelve': r'''A “shelf” is a persistent, dictionary-like object.  The difference
with “dbm” databases is that the values (not the keys!) in a shelf can
be essentially arbitrary Python objects — anything that the "pickle"
module can handle. This includes most class instances, recursive data
types, and objects containing lots of shared  sub-objects.  The keys
are ordinary strings.''',
    'shlex': r'''The "shlex" class makes it easy to write lexical analyzers for simple
syntaxes resembling that of the Unix shell.  This will often be useful
for writing minilanguages, (for example, in run control files for
Python applications) or for parsing quoted strings.''',
    'shutil': r'''The "shutil" module offers a number of high-level operations on files
and collections of files.  In particular, functions are provided
which support file copying and removal. For operations on individual
files, see also the "os" module.''',
    'signal': r'''This module provides mechanisms to use signal handlers in Python.''',
    'site': r'''**This module is automatically imported during initialization.** The
automatic import can be suppressed using the interpreter’s "-S"
option.''',
    'smtpd': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.12 after being deprecated in Python 3.6.  The
removal was decided in **PEP 594**.

A possible replacement is the third-party aiosmtpd library. This
library is not maintained or supported by the Python core team.

The last version of Python that provided the "smtpd" module was Python
3.11.''',
    'smtplib': r'''The "smtplib" module defines an SMTP client session object that can be
used to send mail to any internet machine with an SMTP or ESMTP
listener daemon.  For details of SMTP and ESMTP operation, consult
**RFC 821** (Simple Mail Transfer Protocol) and **RFC 1869** (SMTP
Service Extensions).''',
    'sndhdr': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

Possible replacements are third-party modules from PyPI: filetype,
puremagic, or python-magic. These are not supported or maintained by
the Python core team.

The last version of Python that provided the "sndhdr" module was
Python 3.12.''',
    'socket': r'''This module provides access to the BSD *socket* interface. It is
available on all modern Unix systems, Windows, MacOS, and probably
additional platforms.''',
    'socketserver': r'''The "socketserver" module simplifies the task of writing network
servers.''',
    'spwd': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

A possible replacement is the third-party library python-pam. This
library is not supported or maintained by the Python core team.

The last version of Python that provided the "spwd" module was Python
3.12.''',
    'sqlite3': r'''SQLite is a C library that provides a lightweight disk-based database
that doesn’t require a separate server process and allows accessing
the database using a nonstandard variant of the SQL query language.
Some applications can use SQLite for internal data storage.  It’s also
possible to prototype an application using SQLite and then port the
code to a larger database such as PostgreSQL or Oracle.''',
    'ssl': r'''This module provides access to Transport Layer Security (often known
as “Secure Sockets Layer”) encryption and peer authentication
facilities for network sockets, both client-side and server-side.
This module uses the OpenSSL library. It is available on all modern
Unix systems, Windows, macOS, and probably additional platforms, as
long as OpenSSL is installed on that platform.''',
    'stat': r'''The "stat" module defines constants and functions for interpreting the
results of "os.stat()", "os.fstat()" and "os.lstat()" (if they exist).
For complete details about the "stat()", "fstat()" and "lstat()"
calls, consult the documentation for your system.''',
    'statistics': r'''This module provides functions for calculating mathematical statistics
of numeric ("Real"-valued) data.''',
    'stdtypes': r'''The following sections describe the standard types that are built into
the interpreter.''',
    'string': r'''Text Sequence Type — str''',
    'string.templatelib': r'''Format strings''',
    'stringprep': r'''When identifying things (such as host names) in the internet, it is
often necessary to compare such identifications for “equality”.
Exactly how this comparison is executed may depend on the application
domain, e.g. whether it should be case-insensitive or not. It may be
also necessary to restrict the possible identifications, to allow only
identifications consisting of “printable” characters.''',
    'struct': r'''This module converts between Python values and C structs represented
as Python "bytes" objects.  Compact format strings describe the
intended conversions to/from Python values. The module’s functions and
objects can be used for two largely distinct applications, data
exchange with external sources (files or network connections), or data
transfer between the Python application and the C layer.''',
    'subprocess': r'''The "subprocess" module allows you to spawn new processes, connect to
their input/output/error pipes, and obtain their return codes.  This
module intends to replace several older modules and functions:''',
    'sunau': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "sunau" module was Python
3.12.''',
    'symtable': r'''Symbol tables are generated by the compiler from AST just before
bytecode is generated.  The symbol table is responsible for
calculating the scope of every identifier in the code.  "symtable"
provides an interface to examine these tables.''',
    'sys': r'''This module provides access to some variables used or maintained by
the interpreter and to functions that interact strongly with the
interpreter. It is always available. Unless explicitly noted
otherwise, all variables are read-only.''',
    'sys.monitoring': r'''"sys.monitoring" is a namespace within the "sys" module, not an
independent module, so there is no need to "import sys.monitoring",
simply "import sys" and then use "sys.monitoring".''',
    'sys_path_init': r'''A module search path is initialized when Python starts. This module
search path may be accessed at "sys.path".''',
    'sysconfig': r'''The "sysconfig" module provides access to Python’s configuration
information like the list of installation paths and the configuration
variables relevant for the current platform.''',
    'syslog': r'''This module provides an interface to the Unix "syslog" library
routines. Refer to the Unix manual pages for a detailed description of
the "syslog" facility.''',
    'tabnanny': r'''For the time being this module is intended to be called as a script.
However it is possible to import it into an IDE and use the function
"check()" described below.''',
    'tarfile': r'''The "tarfile" module makes it possible to read and write tar archives,
including those using gzip, bz2 and lzma compression. Use the
"zipfile" module to read or write ".zip" files, or the higher-level
functions in shutil.''',
    'telnetlib': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

Possible replacements are third-party libraries from PyPI: telnetlib3
or Exscript.  These are not supported or maintained by the Python core
team.

The last version of Python that provided the "telnetlib" module was
Python 3.12.''',
    'tempfile': r'''This module creates temporary files and directories.  It works on all
supported platforms. "TemporaryFile", "NamedTemporaryFile",
"TemporaryDirectory", and "SpooledTemporaryFile" are high-level
interfaces which provide automatic cleanup and can be used as *context
managers*. "mkstemp()" and "mkdtemp()" are lower-level functions which
require manual cleanup.''',
    'termios': r'''This module provides an interface to the POSIX calls for tty I/O
control. For a complete description of these calls, see *termios(3)*
Unix manual page.  It is only available for those Unix versions that
support POSIX *termios* style tty I/O control configured during
installation.''',
    'test': r'''The "test" package is meant for internal use by Python only. It is
documented for the benefit of the core developers of Python. Any use
of this package outside of Python’s standard library is discouraged as
code mentioned here can change or be removed without notice between
releases of Python.''',
    'textwrap': r'''The "textwrap" module provides some convenience functions, as well as
"TextWrapper", the class that does all the work. If you’re just
wrapping or filling one or two text strings, the convenience functions
should be good enough; otherwise, you should use an instance of
"TextWrapper" for efficiency.''',
    'threading': r'''This module constructs higher-level threading interfaces on top of the
lower level "_thread" module.''',
    'time': r'''This module provides various time-related functions. For related
functionality, see also the "datetime" and "calendar" modules.''',
    'timeit': r'''This module provides a simple way to time small bits of Python code.
It has both a Command-Line Interface as well as a callable one.  It
avoids a number of common traps for measuring execution times. See
also Tim Peters’ introduction to the “Algorithms” chapter in the
second edition of *Python Cookbook*, published by O’Reilly.''',
    'tk': r'''Tk/Tcl has long been an integral part of Python.  It provides a robust
and platform independent windowing toolkit, that is available to
Python programmers using the "tkinter" package, and its extension, the
"tkinter.ttk" module.''',
    'tkinter': r'''The "tkinter" package (“Tk interface”) is the standard Python
interface to the Tcl/Tk GUI toolkit.  Both Tk and "tkinter" are
available on most Unix platforms, including macOS, as well as on
Windows systems.''',
    'tkinter.colorchooser': r'''The "tkinter.colorchooser" module provides the "Chooser" class as an
interface to the native color picker dialog. "Chooser" implements a
modal color choosing dialog window. The "Chooser" class inherits from
the "Dialog" class.''',
    'tkinter.dnd': r'''This is experimental and due to be deprecated when it is replaced with
the Tk DND.''',
    'tkinter.font': r'''The "tkinter.font" module provides the "Font" class for creating and
using named fonts.''',
    'tkinter.messagebox': r'''The "tkinter.messagebox" module provides a template base class as well
as a variety of convenience methods for commonly used configurations.
The message boxes are modal and will return a subset of ("True",
"False", "None", "OK", "CANCEL", "YES", "NO") based on the user’s
selection. Common message box styles and layouts include but are not
limited to:''',
    'tkinter.scrolledtext': r'''The "tkinter.scrolledtext" module provides a class of the same name
which implements a basic text widget which has a vertical scroll bar
configured to do the “right thing.”  Using the "ScrolledText" class is
a lot easier than setting up a text widget and scroll bar directly.''',
    'tkinter.ttk': r'''The "tkinter.ttk" module provides access to the Tk themed widget set,
introduced in Tk 8.5. It provides additional benefits including anti-
aliased font rendering under X11 and window transparency (requiring a
composition window manager on X11).''',
    'token': r'''This module provides constants which represent the numeric values of
leaf nodes of the parse tree (terminal tokens).  Refer to the file
"Grammar/Tokens" in the Python distribution for the definitions of the
names in the context of the language grammar.  The specific numeric
values which the names map to may change between Python versions.''',
    'tokenize': r'''The "tokenize" module provides a lexical scanner for Python source
code, implemented in Python.  The scanner in this module returns
comments as tokens as well, making it useful for implementing “pretty-
printers”, including colorizers for on-screen displays.''',
    'tomllib': r'''This module provides an interface for parsing TOML 1.0.0 (Tom’s
Obvious Minimal Language, https://toml.io). This module does not
support writing TOML.''',
    'trace': r'''The "trace" module allows you to trace program execution, generate
annotated statement coverage listings, print caller/callee
relationships and list functions executed during a program run.  It
can be used in another program or from the command line.''',
    'traceback': r'''This module provides a standard interface to extract, format and print
stack traces of Python programs. It is more flexible than the
interpreter’s default traceback display, and therefore makes it
possible to configure certain aspects of the output. Finally, it
contains a utility for capturing enough information about an exception
to print it later, without the need to save a reference to the actual
exception. Since exceptions can be the roots of large objects graph,
this utility can significantly improve memory management.''',
    'tracemalloc': r'''The tracemalloc module is a debug tool to trace memory blocks
allocated by Python. It provides the following information:''',
    'tty': r'''The "tty" module defines functions for putting the tty into cbreak and
raw modes.''',
    'turtle': r'''Turtle graphics is an implementation of the popular geometric drawing
tools introduced in Logo, developed by Wally Feurzeig, Seymour Papert
and Cynthia Solomon in 1967.''',
    'types': r'''This module defines utility functions to assist in dynamic creation of
new types.''',
    'typing': r'''The Python runtime does not enforce function and variable type
annotations. They can be used by third party tools such as *type
checkers*, IDEs, linters, etc.''',
    'unicodedata': r'''This module provides access to the Unicode Character Database (UCD)
which defines character properties for all Unicode characters. The
data contained in this database is compiled from the UCD version
16.0.0.''',
    'unittest': r'''(If you are already familiar with the basic concepts of testing, you
might want to skip to the list of assert methods.)''',
    'unittest.mock': r'''"unittest.mock" is a library for testing in Python. It allows you to
replace parts of your system under test with mock objects and make
assertions about how they have been used.''',
    'unittest.mock-examples': r'''Common uses for "Mock" objects include:''',
    'urllib': r'''"urllib" is a package that collects several modules for working with
URLs:''',
    'urllib.error': r'''The "urllib.error" module defines the exception classes for exceptions
raised by "urllib.request".  The base exception class is "URLError".''',
    'urllib.parse': r'''This module defines a standard interface to break Uniform Resource
Locator (URL) strings up in components (addressing scheme, network
location, path etc.), to combine the components back into a URL
string, and to convert a “relative URL” to an absolute URL given a
“base URL.”''',
    'urllib.request': r'''The "urllib.request" module defines functions and classes which help
in opening URLs (mostly HTTP) in a complex world — basic and digest
authentication, redirections, cookies and more.''',
    'urllib.robotparser': r'''This module provides a single class, "RobotFileParser", which answers
questions about whether or not a particular user agent can fetch a URL
on the web site that published the "robots.txt" file.  For more
details on the structure of "robots.txt" files, see
http://www.robotstxt.org/orig.html.''',
    'uu': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "uu" module was Python
3.12.''',
    'uuid': r'''This module provides immutable "UUID" objects (the "UUID" class) and
functions for generating UUIDs corresponding to a specific UUID
version as specified in **RFC 9562** (which supersedes **RFC 4122**),
for example, "uuid1()" for UUID version 1, "uuid3()" for UUID version
3, and so on. Note that UUID version 2 is deliberately omitted as it
is outside the scope of the RFC.''',
    'venv': r'''The "venv" module supports creating lightweight “virtual
environments”, each with their own independent set of Python packages
installed in their "site" directories. A virtual environment is
created on top of an existing Python installation, known as the
virtual environment’s “base” Python, and by default is isolated from
the packages in the base environment, so that only those explicitly
installed in the virtual environment are available. See Virtual
Environments and "site"’s virtual environments documentation for more
information.''',
    'warnings': r'''Warning messages are typically issued in situations where it is useful
to alert the user of some condition in a program, where that condition
(normally) doesn’t warrant raising an exception and terminating the
program.  For example, one might want to issue a warning when a
program uses an obsolete module.''',
    'wave': r'''The "wave" module provides a convenient interface to the Waveform
Audio “WAVE” (or “WAV”) file format. Only uncompressed PCM encoded
wave files are supported.''',
    'weakref': r'''The "weakref" module allows the Python programmer to create *weak
references* to objects.''',
    'webbrowser': r'''The "webbrowser" module provides a high-level interface to allow
displaying web-based documents to users. Under most circumstances,
simply calling the "open()" function from this module will do the
right thing.''',
    'windows': r'''This chapter describes modules that are only available on MS Windows
platforms.''',
    'winreg': r'''These functions expose the Windows registry API to Python.  Instead of
using an integer as the registry handle, a handle object is used to
ensure that the handles are closed correctly, even if the programmer
neglects to explicitly close them.''',
    'winsound': r'''The "winsound" module provides access to the basic sound-playing
machinery provided by Windows platforms.  It includes functions and
several constants.''',
    'wsgiref': r'''The Web Server Gateway Interface (WSGI) is a standard interface
between web server software and web applications written in Python.
Having a standard interface makes it easy to use an application that
supports WSGI with a number of different web servers.''',
    'xdrlib': r'''This module is no longer part of the Python standard library. It was
removed in Python 3.13 after being deprecated in Python 3.11.  The
removal was decided in **PEP 594**.

The last version of Python that provided the "xdrlib" module was
Python 3.12.''',
    'xml': r'''Python’s interfaces for processing XML are grouped in the "xml"
package.''',
    'xml.dom': r'''The Document Object Model, or “DOM,” is a cross-language API from the
World Wide Web Consortium (W3C) for accessing and modifying XML
documents.  A DOM implementation presents an XML document as a tree
structure, or allows client code to build such a structure from
scratch.  It then gives access to the structure through a set of
objects which provided well-known interfaces.''',
    'xml.dom.minidom': r'''"xml.dom.minidom" is a minimal implementation of the Document Object
Model interface, with an API similar to that in other languages.  It
is intended to be simpler than the full DOM and also significantly
smaller.  Users who are not already proficient with the DOM should
consider using the "xml.etree.ElementTree" module for their XML
processing instead.''',
    'xml.dom.pulldom': r'''The "xml.dom.pulldom" module provides a “pull parser” which can also
be asked to produce DOM-accessible fragments of the document where
necessary. The basic concept involves pulling “events” from a stream
of incoming XML and processing them. In contrast to SAX which also
employs an event-driven processing model together with callbacks, the
user of a pull parser is responsible for explicitly pulling events
from the stream, looping over those events until either processing is
finished or an error condition occurs.''',
    'xml.etree.elementtree': r'''The "xml.etree.ElementTree" module implements a simple and efficient
API for parsing and creating XML data.''',
    'xml.sax': r'''The "xml.sax" package provides a number of modules which implement the
Simple API for XML (SAX) interface for Python.  The package itself
provides the SAX exceptions and the convenience functions which will
be most used by users of the SAX API.''',
    'xml.sax.handler': r'''The SAX API defines five kinds of handlers: content handlers, DTD
handlers, error handlers, entity resolvers and lexical handlers.
Applications normally only need to implement those interfaces whose
events they are interested in; they can implement the interfaces in a
single object or in multiple objects. Handler implementations should
inherit from the base classes provided in the module
"xml.sax.handler", so that all methods get default implementations.''',
    'xml.sax.reader': r'''SAX parsers implement the "XMLReader" interface. They are implemented
in a Python module, which must provide a function "create_parser()".
This function is invoked by  "xml.sax.make_parser()" with no arguments
to create a new  parser object.''',
    'xml.sax.utils': r'''The module "xml.sax.saxutils" contains a number of classes and
functions that are commonly useful when creating SAX applications,
either in direct use, or as base classes.''',
    'xmlrpc': r'''XML-RPC is a Remote Procedure Call method that uses XML passed via
HTTP as a transport.  With it, a client can call methods with
parameters on a remote server (the server is named by a URI) and get
back structured data.''',
    'xmlrpc.client': r'''XML-RPC is a Remote Procedure Call method that uses XML passed via
HTTP(S) as a transport.  With it, a client can call methods with
parameters on a remote server (the server is named by a URI) and get
back structured data.  This module supports writing XML-RPC client
code; it handles all the details of translating between conformable
Python objects and XML on the wire.''',
    'xmlrpc.server': r'''The "xmlrpc.server" module provides a basic server framework for XML-
RPC servers written in Python.  Servers can either be free standing,
using "SimpleXMLRPCServer", or embedded in a CGI environment, using
"CGIXMLRPCRequestHandler".''',
    'zipapp': r'''This module provides tools to manage the creation of zip files
containing Python code, which can be  executed directly by the Python
interpreter.  The module provides both a Command-Line Interface and a
Python API.''',
    'zipfile': r'''The ZIP file format is a common archive and compression standard. This
module provides tools to create, read, write, append, and list a ZIP
file.  Any advanced use of this module will require an understanding
of the format, as defined in PKZIP Application Note.''',
    'zipimport': r'''This module adds the ability to import Python modules ("*.py",
"*.pyc") and packages from ZIP-format archives. It is usually not
needed to use the "zipimport" module explicitly; it is automatically
used by the built-in "import" mechanism for "sys.path" items that are
paths to ZIP archives.''',
    'zlib': r'''For applications that require data compression, the functions in this
module allow compression and decompression, using the zlib library.
The zlib library has its own home page at https://www.zlib.net.
There are known incompatibilities between the Python module and
versions of the zlib library earlier than 1.1.3; 1.1.3 has a security
vulnerability, so we recommend using 1.1.4 or later.''',
    'zoneinfo': r'''The "zoneinfo" module provides a concrete time zone implementation to
support the IANA time zone database as originally specified in **PEP
615**. By default, "zoneinfo" uses the system’s time zone data if
available; if no system time zone data is available, the library will
fall back to using the first-party tzdata package available on PyPI.''',
}
