#!usr/bin/env python3

import os
import tomllib
import contextlib

from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
DEST = ROOT.parent.parent / "Objects" / "dunder_docs_generated.c"

TYPE_MAP = {"str": "PyUnicode"}


def c_escape(s):
    return '"' + s.replace("\\", "\\\\").replace('"', r"\"").replace("\n", r"\n") + '"'


with DEST.open("w") as f:
    with contextlib.redirect_stdout(f):
        print("/* Auto-generated by Tools/dunder_docs/make_dunder_docs.py */\n")
        print('#include "Python.h"')
        print('#include "pycore_global_strings.h"')
        print('#include "pycore_dunder_docs.h"')
        print()
        print("int")
        print("_Py_BuildDunderDocs(PyObject *target) {")
        print("    PyObject *dict;")
        print("    PyObject *field;")
        print("    PyObject *descr;")
        for type_fname in DATA.iterdir():
            if type_fname.suffix != ".toml":
                continue
            type_ = type_fname.stem
            print()
            print()
            print(f"    /* {type_.upper()} */")
            c_typename = TYPE_MAP.get(type_, f"Py{type_.title()}")
            print(f"    dict = PyType_GetDict(&{c_typename}_Type);")
            with open(type_fname, "rb") as type_file:
                toml = tomllib.load(type_file)
                for field, doc in toml.items():
                    print(f"    field = PyUnicode_FromString({c_escape(field)});")
                    print(f"    descr = PyDict_GetItem(dict, field);")

                    print(
                        f"    ((PyWrapperDescrObject *)descr)->doc = {c_escape(doc)};"
                    )
                    print(f"    Py_DECREF(field);")
                    print()
            print(f"    Py_DECREF(dict);")
            print(f"    return 0;")
        print("};")
