from time import asctime

from docutils import nodes
from sphinx.builders.text import TextBuilder
from sphinx.util.display import status_iterator
from sphinx.util.docutils import new_document
from sphinx.writers.text import TextTranslator

SKIP_PAGES = {
    '__main__',
}


def _repr(text: str, /) -> str:
    """Return a triple-single-quoted representation of text."""
    if "'''" not in text:
        return f"r'''{text}'''"
    text = text.replace("\\", "\\\\").replace("'''", r"\'\'\'")
    return f"'''{text}'''"


class PyDocLibrarySummaryBuilder(TextBuilder):
    """
    Collect the first paragraph from every document in the library, for use in
    providing meaningful intros for the built-in help function
    """

    name = "pydoc-library"

    def init(self):
        super().init()
        self.summaries = {}

    def get_outdated_docs(self):
        return "summaries of the library modules"

    def write_documents(self, _docnames):
        env = self.env

        candidates = sorted(
            d
            for d in env.found_docs
            if (d == "library" or d.startswith("library/"))
        )

        for path in status_iterator(
            candidates,
            "extracting library summaries... ",
            length=len(candidates),
        ):
            if path.removeprefix('library/') in SKIP_PAGES:
                continue

            doctree = env.get_and_resolve_doctree(path, builder=self)

            paragraph_iter = iter(doctree.traverse(nodes.paragraph))
            paragraphs = []
            while True:
                para = next(paragraph_iter, None)
                if para is None:
                    break

                rawsource = para.rawsource
                if (
                    "Source code:" in rawsource
                    or rawsource.startswith("Added in version")
                    or rawsource.startswith("Deprecated since version")
                    or rawsource.startswith("Note:")
                ):
                    # skip certain first 'paragraphs' that aren't actually
                    # descriptive
                    continue

                if rawsource.startswith(
                    "The modules described in this chapter"
                ):
                    # don't even try to render the summary 'chapters'
                    break

                docname = path.removeprefix("library/")
                paragraphs.append(para)

                if rawsource.startswith(
                    "This module is no longer part of the Python standard library"
                ):
                    # It seems like all of these have follow-up text that
                    # describes alternatives, where to get more information,
                    # etc.  So let's include that as well.
                    curtext = para.children[0]
                    para.children[0] = nodes.Text(
                        curtext.replace('This module', docname)
                    )
                    paragraphs.extend(paragraph_iter)
                if rawsource.endswith(':'):
                    # maybe the next node is a bulleted list or similar?
                    # add it to our source
                    paragraphs.append(
                        para.traverse(
                            descend=False,
                            include_self=False,
                            siblings=True,
                            ascend=False,
                        )[0]
                    )
                break

            if not paragraphs:
                # no meaningful text? skip
                continue

            document = new_document("<summary>")
            document.extend(paragraphs)
            visitor = TextTranslator(document, builder=self)
            document.walkabout(visitor)
            text = "\n".join(visitor.body.splitlines(False))

            self.summaries[docname] = text

    def finish(self) -> None:
        output_file = self.outdir / "library.py"
        library_repr = "\n".join(
            f"    '{docname}': {_repr(self.summaries[docname])},"
            for docname in sorted(self.summaries)
        )
        output_file.write_text(
            f"""\
# The contents of this file were automatically generated by Sphinx, based on
# the documentation in Doc/library in the CPython source tree.  This file was
# generated on {asctime()}.

library = {{
{library_repr}
}}
"""
        )


def setup(app):
    app.add_builder(PyDocLibrarySummaryBuilder)
    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
