import json
from time import asctime

from docutils import nodes
from sphinx.builders.text import TextBuilder
from sphinx.util.display import status_iterator
from sphinx.util.docutils import new_document
from sphinx.writers.text import TextTranslator


class PyDocLibrarySummaryBuilder(TextBuilder):
    """
    Collect the first paragraph from every document in the libarary
    """

    name = "pydoc-library"

    def init(self):
        super().init()
        self.paras = {}

    def get_outdated_docs(self):
        return "summaries of the library modules"

    def write_documents(self, _docnames):
        env = self.env

        candidates = sorted(
            d
            for d in env.found_docs
            if (d == "library" or d.startswith("library/"))
        )

        for docname in status_iterator(
            candidates,
            "extracting library summaries... ",
            length=len(candidates),
        ):
            doctree = env.get_and_resolve_doctree(docname, builder=self)

            paragraph_gen = (n for n in doctree.traverse(nodes.paragraph))
            paragraphs = []
            while True:
                para = next(paragraph_gen, None)
                if para is None:
                    break

                rawsource = para.rawsource
                if (
                    "Source code:" in rawsource
                    or rawsource.startswith("Added in version")
                    or rawsource.startswith("Deprecated since version")
                    or rawsource.startswith("Note:")
                ):
                    # skip certain first 'paragraphs' that aren't actually
                    # descriptive
                    continue

                if rawsource.startswith(
                    "The modules described in this chapter"
                ):
                    # don't even try to render the summary 'chapters'
                    break

                paragraphs.append(para)

                if rawsource.startswith(
                    "This module is no longer part of the Python standard library"
                ):
                    # It seems like all of these have follow-up text that
                    # describes alternatives, where to get more information,
                    # etc.  So let's include that as well.
                    paragraphs.extend(paragraph_gen)
                break

            if not paragraphs:
                # no meaningful text? skip
                continue

            document = new_document("<summary>")
            document.extend(paragraphs)
            visitor = TextTranslator(document, builder=self)
            document.walkabout(visitor)
            text = "\n".join(map(str.rstrip, visitor.body.splitlines()))

            self.paras[docname.removeprefix("library/")] = text

    def finish(self) -> None:
        output_file = self.outdir / "library.py"
        output_file.write_text(
            f"""\
# Autogenerated by Sphinx on {asctime()}
# as part of the release process.

library = {json.dumps(self.paras, indent=4)}
"""
        )


def setup(app):
    app.add_builder(PyDocLibrarySummaryBuilder)
    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
